Hack: dyld: Symbol not found: Only for Mac OS: XAMPP
This is a hack to resolve the following error - only for Mac OS XAMPP
1.8.2, since  changing envvars of XAMPP does not work for me.

dyld: Symbol not found: __cg_jpeg_resync_to_restart
  Referenced from:
/System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
  Expected in: /Applications/XAMPP/xamppfiles/lib/libJPEG.dylib
 in /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO